CREATE TABLE DOCUMENT (
    ID                 INTEGER NOT NULL,
    CLIENTID           INTEGER NOT NULL,
    AGENTID            INTEGER NOT NULL,
    DOCTYPEID          SMALLINT NOT NULL,
    OUTERCLIENTLINKID  INTEGER,
    DOCDATE            TIMESTAMP NOT NULL,
    DISCOUNT           DOUBLE PRECISION DEFAULT 0,
    SALETYPE           SMALLINT NOT NULL,
    TERMDATE           TIMESTAMP,
    SUMWITHOUTVAT      DOUBLE PRECISION,
    SUMWITHVAT         DOUBLE PRECISION,
    SENDINGDATE        TIMESTAMP,
    EXPORTED           SMALLINT DEFAULT 0 NOT NULL,
    DESCRIPT           VARCHAR(255),
    REGNUM             VARCHAR(35),
    LONGITUDE          DOUBLE PRECISION DEFAULT 0.0,
    LATITUDE           DOUBLE PRECISION DEFAULT 0.0,
    ITEMCOUNT          DOUBLE PRECISION
);

ALTER TABLE DOCUMENT ADD PRIMARY KEY (ID);

ALTER TABLE DOCUMENT ADD CONSTRAINT FK_DOCUMENT_AGENTID FOREIGN KEY (AGENTID) REFERENCES AGENTS (ID) ON UPDATE CASCADE;
ALTER TABLE DOCUMENT ADD CONSTRAINT FK_DOCUMENT_CLIENT FOREIGN KEY (CLIENTID) REFERENCES CLIENT (ID) ON UPDATE CASCADE;
ALTER TABLE DOCUMENT ADD CONSTRAINT FK_DOCUMENT_DOCTYPE FOREIGN KEY (DOCTYPEID) REFERENCES DOCTYPE (ID) ON UPDATE CASCADE;

CREATE SEQUENCE GEN_DOCUMENT_ID;
ALTER SEQUENCE GEN_DOCUMENT_ID RESTART WITH 1000;

CREATE TABLE DOCUMENTDET (
    ID               INTEGER NOT NULL,
    DOCID            INTEGER NOT NULL,
    GOODSID          INTEGER NOT NULL,
    ITEMCOUNT        DOUBLE PRECISION NOT NULL,
    PRICEWITHOUTVAT  DOUBLE PRECISION,
    PRICEWITHVAT     DOUBLE PRECISION
);

ALTER TABLE DOCUMENTDET ADD PRIMARY KEY (ID);

ALTER TABLE DOCUMENTDET ADD CONSTRAINT FK_DOCUMENTDET_1 FOREIGN KEY (DOCID) REFERENCES DOCUMENT (ID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE DOCUMENTDET ADD CONSTRAINT FK_DOCUMENTDET_GOODSID FOREIGN KEY (GOODSID) REFERENCES GOODS (ID) ON UPDATE CASCADE;

CREATE SEQUENCE GEN_DOCDETAIL_ID;
ALTER SEQUENCE GEN_DOCDETAIL_ID RESTART WITH 1000;