CREATE TABLE ROUTES (
    ID       INTEGER NOT NULL,
    SNAME    VARCHAR(35),
    OUTERID  INTEGER
);

ALTER TABLE ROUTES ADD CONSTRAINT PK_ROUTES PRIMARY KEY (ID);
CREATE INDEX ROUTES_OUTERID ON ROUTES (OUTERID, ID);

CREATE TABLE CLIENTGROUP (
    ID       INTEGER NOT NULL,
    SNAME    VARCHAR(100),
    OUTERID  INTEGER
);

ALTER TABLE CLIENTGROUP ADD CONSTRAINT PK_CLIENTGROUP PRIMARY KEY (ID);
CREATE INDEX CLIENTGROUP_OUTERID ON CLIENTGROUP (OUTERID, ID);

CREATE TABLE AGENTS (
    ID            INTEGER NOT NULL,
    ISACTIVE      SMALLINT DEFAULT 1,
    SNAME         VARCHAR(35),
    SUPERVISORID  INTEGER,
    ROLECODE      SMALLINT DEFAULT 1 NOT NULL,
    USERID        INTEGER,
    OUTERID       INTEGER
);

ALTER TABLE AGENTS ADD CONSTRAINT PK_AGENTS PRIMARY KEY (ID);
CREATE INDEX AGENTS_OUTERID ON AGENTS (OUTERID, ID);

CREATE TABLE CLIENT (
    ID               INTEGER NOT NULL,
    AGENTID          INTEGER NOT NULL,
    PARENTID         INTEGER,
    NAME             VARCHAR(35),
    DEBTSUMM1        INTEGER,
    DEBTDAYS1        INTEGER,
    DEBTSUMM2        INTEGER,
    DEBTDAYS2        INTEGER,
    STOPSHIPMENT     SMALLINT,
    ROUTEID          SMALLINT,
    DEFAULTDISCOUNT  INTEGER,
    NOACTIVE         SMALLINT DEFAULT 0 NOT NULL,
    ADDRESSLOCATION  VARCHAR(84),
    PHONE            VARCHAR(15),
    TAXCODE          VARCHAR(15),
    TAXNUM           VARCHAR(10),
    OKPO             VARCHAR(15),
    MFO              CHAR(10),
    BANKNAME         VARCHAR(50),
    BANKACCOUNT      VARCHAR(15),
    DOGNUM           VARCHAR(20),
    FNAME            VARCHAR(84),
    ADDRESSLAW       VARCHAR(84),
    CLIENTTYPEID     INTEGER DEFAULT -1 NOT NULL,
    LONGITUDE        DOUBLE PRECISION,
    LATITUDE         DOUBLE PRECISION,
    OUTERID          INTEGER
);

ALTER TABLE CLIENT ADD CONSTRAINT UNQ1_CLIENT UNIQUE (AGENTID, ID, OUTERID);
ALTER TABLE CLIENT ADD CONSTRAINT PK_CLIENT PRIMARY KEY (ID);
ALTER TABLE CLIENT ADD CONSTRAINT FK_CLIENT_CLIENTGROUP FOREIGN KEY (CLIENTTYPEID) REFERENCES CLIENTGROUP (ID) ON DELETE SET DEFAULT ON UPDATE CASCADE;
ALTER TABLE CLIENT ADD CONSTRAINT FK_ROUTESID FOREIGN KEY (ROUTEID) REFERENCES ROUTES (ID) ON DELETE SET NULL ON UPDATE CASCADE;
CREATE INDEX CLIENT_OUTERID ON CLIENT (OUTERID, ID);

CREATE SEQUENCE GEN_AGENTS_ID;
ALTER SEQUENCE GEN_AGENTS_ID RESTART WITH 10000;

CREATE SEQUENCE GEN_CLIENT_ID;
ALTER SEQUENCE GEN_CLIENT_ID RESTART WITH 20000;