CREATE TABLE LOCATION_SAVE_STATE (
    ID INTEGER NOT NULL,
    NAME VARCHAR(100) NOT NULL);
    
ALTER TABLE LOCATION_SAVE_STATE
ADD CONSTRAINT PK_LOCATION_SAVE_STATE
PRIMARY KEY (ID);

INSERT INTO LOCATION_SAVE_STATE (ID, NAME)
                         VALUES (0, 'Unknown');
INSERT INTO LOCATION_SAVE_STATE (ID, NAME)
                         VALUES (1, 'Success');
INSERT INTO LOCATION_SAVE_STATE (ID, NAME)
                         VALUES (2, 'GPS is off');
INSERT INTO LOCATION_SAVE_STATE (ID, NAME)
                         VALUES (3, 'Time is over');
INSERT INTO LOCATION_SAVE_STATE (ID, NAME)
                         VALUES (4, 'Device on');
INSERT INTO LOCATION_SAVE_STATE (ID, NAME)
                         VALUES (5, 'Device off');

COMMIT WORK;

ALTER TABLE LOCATION
ADD CONSTRAINT FK_LOCATION_SAVE_STATE
FOREIGN KEY (SAVESTATE)
REFERENCES LOCATION_SAVE_STATE(ID)
ON DELETE SET NULL
ON UPDATE CASCADE;

ALTER TABLE GOODS
ADD CONSTRAINT FK_GOODS_GROUP
FOREIGN KEY (CATEGORYID)
REFERENCES GOODSGROUP(ID)
ON DELETE SET DEFAULT
ON UPDATE CASCADE;
