CREATE TABLE LOCATION (
    LONGITUDE   DOUBLE PRECISION,
    LATITUDE    DOUBLE PRECISION,
    CLOCK       TIMESTAMP,
    PROVIDER    VARCHAR(10),
    ACCURACY    INTEGER,
    SEARCHTIME  INTEGER,
    SAVESTATE   INTEGER,
    CHECKINS    INTEGER,
    AGENTID     INTEGER,
    BATTERY     INTEGER,
    ID          INTEGER NOT NULL
);

ALTER TABLE LOCATION ADD PRIMARY KEY (ID);

ALTER TABLE LOCATION ADD CONSTRAINT FK_LOCATION_SAVE_STATE FOREIGN KEY (SAVESTATE) REFERENCES LOCATION_SAVE_STATE (ID) ON UPDATE CASCADE;

CREATE SEQUENCE GEN_LOCATION_ID;
ALTER SEQUENCE GEN_LOCATION_ID RESTART WITH 1000;