CREATE TABLE JOBS (
    NAME      VARCHAR(255),
    ID        INTEGER NOT NULL,
    ROLENAME  VARCHAR(255)
);

ALTER TABLE JOBS ADD CONSTRAINT PK_JOBS PRIMARY KEY (ID);

CREATE TABLE PART (
    ID        INTEGER NOT NULL,
    PARENTID  INTEGER,
    PARTNAME  VARCHAR(255),
    SORTPOS   INTEGER DEFAULT 0,
    ROLENAME  VARCHAR(255)
);

ALTER TABLE PART ADD CONSTRAINT PK_PART PRIMARY KEY (ID);
ALTER TABLE PART ADD CONSTRAINT FK_PART_PARENT FOREIGN KEY (PARENTID) REFERENCES PART (ID) ON DELETE SET NULL ON UPDATE CASCADE;

CREATE TABLE PARTJOBSFORUSERS (
    ID        INTEGER NOT NULL,
    JOBSID    INTEGER NOT NULL,
    ISACTIVE  SMALLINT NOT NULL,
    PARTID    INTEGER NOT NULL,
    USERID    INTEGER NOT NULL
);

ALTER TABLE PARTJOBSFORUSERS ADD CONSTRAINT PK_PARTJOBSFORUSERS PRIMARY KEY (ID);
ALTER TABLE PARTJOBSFORUSERS ADD CONSTRAINT FK_PARTJOBSFORUSERS_JOBSID FOREIGN KEY (JOBSID) REFERENCES JOBS (ID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE PARTJOBSFORUSERS ADD CONSTRAINT FK_PARTJOBSFORUSERS_PARTID FOREIGN KEY (PARTID) REFERENCES PART (ID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE PARTJOBSFORUSERS ADD CONSTRAINT FK_PARTJOBSFORUSERS_USERID FOREIGN KEY (USERID) REFERENCES USERS (ID) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE SEQUENCE GEN_JOB_ID;
CREATE SEQUENCE GEN_PART_ID;
CREATE SEQUENCE GEN_PARTJOBSFORUSERS_ID;

ALTER SEQUENCE GEN_JOB_ID RESTART WITH 1000;
ALTER SEQUENCE GEN_PART_ID RESTART WITH 2000;
ALTER SEQUENCE GEN_PARTJOBSFORUSERS_ID RESTART WITH 1000;