CREATE TABLE PAYFORMS (
    ID       INTEGER NOT NULL,
    SNAME    VARCHAR(34),
    OUTERID  INTEGER
);

ALTER TABLE PAYFORMS ADD CONSTRAINT PK_PAYFORMS PRIMARY KEY (ID);

CREATE SEQUENCE GEN_PAYFORM_ID;
ALTER SEQUENCE GEN_PAYFORM_ID RESTART WITH 1000;