CREATE TABLE ROUTES (
    ID       INTEGER NOT NULL,
    SNAME    VARCHAR(35),
    OUTERID  INTEGER
);

ALTER TABLE ROUTES ADD CONSTRAINT PK_ROUTES PRIMARY KEY (ID);
CREATE INDEX ROUTES_OUTERID ON ROUTES (OUTERID, ID);

CREATE TABLE CLIENTGROUP (
    ID       INTEGER NOT NULL,
    SNAME    VARCHAR(100),
    OUTERID  INTEGER
);

ALTER TABLE CLIENTGROUP ADD CONSTRAINT PK_CLIENTGROUP PRIMARY KEY (ID);
CREATE INDEX CLIENTGROUP_OUTERID ON CLIENTGROUP (OUTERID, ID);

CREATE TABLE AGENTS (
    ID            INTEGER NOT NULL,
    ISACTIVE      SMALLINT DEFAULT 1,
    SNAME         VARCHAR(35),
    SUPERVISORID  INTEGER,
    ROLECODE      SMALLINT DEFAULT 1 NOT NULL,
    USERID        INTEGER,
    OUTERID       INTEGER,
    MYCLIENTUID       INTEGER,
    REGNUMNEXT1       INTEGER,
    REGNUMNEXT2       INTEGER,
    VSANDPS           SMALLINT,
    AUTODISCOUNT      INTEGER,
    STRICTSTOPSHIP    SMALLINT DEFAULT 0,
    REGNUMPREFIX1     VARCHAR(5),
    REGNUMPREFIX2     VARCHAR(5),
    FIO               VARCHAR(35),
    EMAIL             VARCHAR(255),
    IMPORTDATETIME    TIMESTAMP DEFAULT current_timestamp,
    UPDATEDATETIME    TIMESTAMP DEFAULT current_date,
    ADMIN_PASS        VARCHAR(100),
    MONEYNAME         VARCHAR(10),
    MONEYFORMAT       VARCHAR(50),
    QTYFORMAT         VARCHAR(50),
    DAYDELDOC         INTEGER,
    ISGPS             SMALLINT DEFAULT 1 NOT NULL,
    FREQUENCYGETGPS   INTEGER,
    FREQUENCYSENDGPS  INTEGER,
    GPSFROMHOUR       INTEGER,
    GPSTOHOUR         INTEGER,
    GPSBYDAY          VARCHAR(13) DEFAULT '1,1,1,1,1,0,0',
    ISAPPSTAT         SMALLINT DEFAULT 0,
    ISGPSBEFOREORDER  SMALLINT DEFAULT 0,
);

ALTER TABLE AGENTS ADD CONSTRAINT PK_AGENTS PRIMARY KEY (ID);
CREATE INDEX AGENTS_OUTERID ON AGENTS (OUTERID, ID);

CREATE TABLE CLIENT (
    ID               INTEGER NOT NULL,
    AGENTID          INTEGER NOT NULL,
    PARENTID         INTEGER,
    NAME             VARCHAR(35),
    DEBTSUMM1        DOUBLE PRECISION,
    DEBTDAYS1        DOUBLE PRECISION,
    DEBTSUMM2        DOUBLE PRECISION,
    DEBTDAYS2        DOUBLE PRECISION,
    STOPSHIPMENT     SMALLINT,
    ROUTEID          SMALLINT,
    DEFAULTDISCOUNT  DOUBLE PRECISION,
    NOACTIVE         SMALLINT DEFAULT 0 NOT NULL,
    ADDRESSLOCATION  VARCHAR(84),
    PHONE            VARCHAR(15),
    TAXCODE          VARCHAR(15),
    TAXNUM           VARCHAR(10),
    OKPO             VARCHAR(15),
    MFO              CHAR(10),
    BANKNAME         VARCHAR(50),
    BANKACCOUNT      VARCHAR(15),
    DOGNUM           VARCHAR(20),
    FNAME            VARCHAR(84),
    ADDRESSLAW       VARCHAR(84),
    CLIENTTYPEID     INTEGER DEFAULT -1 NOT NULL,
    LONGITUDE        DOUBLE PRECISION,
    LATITUDE         DOUBLE PRECISION,
    OUTERID          INTEGER
);

ALTER TABLE CLIENT ADD CONSTRAINT UNQ1_CLIENT UNIQUE (AGENTID, ID, OUTERID);
ALTER TABLE CLIENT ADD CONSTRAINT PK_CLIENT PRIMARY KEY (ID);
ALTER TABLE CLIENT ADD CONSTRAINT FK_CLIENT_CLIENTGROUP FOREIGN KEY (CLIENTTYPEID) REFERENCES CLIENTGROUP (ID) ON DELETE SET DEFAULT ON UPDATE CASCADE;
ALTER TABLE CLIENT ADD CONSTRAINT FK_ROUTESID FOREIGN KEY (ROUTEID) REFERENCES ROUTES (ID) ON DELETE SET NULL ON UPDATE CASCADE;
CREATE INDEX CLIENT_OUTERID ON CLIENT (OUTERID, ID);

CREATE TABLE WSSERVERS (
    ID             INTEGER NOT NULL,
    SERVERADDRESS  VARCHAR(255) NOT NULL,
    DESCRIPTION    VARCHAR(255),
    ISDEFAULT      SMALLINT DEFAULT 0 NOT NULL
);
ALTER TABLE WSSERVERS ADD CONSTRAINT PK_WSSERVERS PRIMARY KEY (ID);

CREATE SEQUENCE GEN_WSSERVERS;
ALTER SEQUENCE GEN_WSSERVERS RESTART WITH 1000;

CREATE TABLE SYSSETS (
    ID                 INTEGER NOT NULL,
    WEBSERVICEADDRESS  VARCHAR(2048),
    BD_VER             VARCHAR(50),
    DBFTYPE            VARCHAR(20),
    MOBILESWAPVERSION  INTEGER
);

ALTER TABLE SYSSETS ADD CONSTRAINT PK_SYSSETS PRIMARY KEY (ID);

CREATE TABLE SERVICECLIENT (
    ID           INTEGER NOT NULL,
    TYPECODE     INTEGER NOT NULL,
    NAME         VARCHAR(50),
    FILEPATH     VARCHAR(255),
    FILEVERSION  VARCHAR(50)
);

ALTER TABLE SERVICECLIENT ADD CONSTRAINT PK_SERVICECLIENT PRIMARY KEY (ID);

CREATE SEQUENCE GEN_SERVICECLIENT;
ALTER SEQUENCE GEN_SERVICECLIENT RESTART WITH 4;

CREATE SEQUENCE GEN_AGENTS_ID;
ALTER SEQUENCE GEN_AGENTS_ID RESTART WITH 10000;

CREATE SEQUENCE GEN_CLIENT_ID;
ALTER SEQUENCE GEN_CLIENT_ID RESTART WITH 20000;

CREATE SEQUENCE GEN_CLIENTGROUP_ID;
ALTER SEQUENCE GEN_CLIENTGROUP_ID RESTART WITH 1000;