CREATE TABLE USERS (
    ID        INTEGER NOT NULL,
    USERFIO   VARCHAR(255),
    USERNAME  VARCHAR(35) NOT NULL,
    PASSWD    VARCHAR(255) NOT NULL,
    ISACTIVE  SMALLINT
);

ALTER TABLE USERS ADD CONSTRAINT UNQ1_USERS_USERNAME UNIQUE (USERNAME)
ALTER TABLE USERS ADD CONSTRAINT PK_USERS PRIMARY KEY (ID);

CREATE TABLE DEVICESERIALNUMBERS (
    ID           INTEGER NOT NULL,
    SN           VARCHAR(255) NOT NULL,
    DESCRIPTION  VARCHAR(255),
    USERID       INTEGER
);

ALTER TABLE DEVICESERIALNUMBERS ADD CONSTRAINT UNQ1_SERIALNUMBERS_SN UNIQUE (SN);
ALTER TABLE DEVICESERIALNUMBERS ADD CONSTRAINT PK_SERIALNUMBERS PRIMARY KEY (ID);
ALTER TABLE DEVICESERIALNUMBERS ADD CONSTRAINT FK_DEVICESERIALNUMBERS_USER FOREIGN KEY (USERID) REFERENCES USERS (ID) ON DELETE SET NULL ON UPDATE CASCADE;

CREATE SEQUENCE GEN_USER_ID;
ALTER SEQUENCE GEN_USER_ID RESTART WITH 1000;

CREATE SEQUENCE GEN_DEVICESERIALNUMBER_ID;
ALTER SEQUENCE GEN_DEVICESERIALNUMBER_ID RESTART WITH 1000;