DELETE FROM AGENTS;
COMMIT WORK;

INSERT INTO AGENTS (ID, ISACTIVE, SNAME, SUPERVISORID, ROLECODE, USERID, OUTERID)
            VALUES (444, 1, '370 Додич', NULL, 2, NULL, 581);
INSERT INTO AGENTS (ID, ISACTIVE, SNAME, SUPERVISORID, ROLECODE, USERID, OUTERID)
            VALUES (495, 1, '32_Кульчицький', NULL, 1, NULL, 3060);
INSERT INTO AGENTS (ID, ISACTIVE, SNAME, SUPERVISORID, ROLECODE, USERID, OUTERID)
            VALUES (496, 1, '33_Клочко', NULL, 1, NULL, 3080);

COMMIT WORK;

DELETE FROM CLIENTGROUP;
COMMIT WORK;

INSERT INTO CLIENTGROUP (ID, SNAME, OUTERID)
                 VALUES (-1, 'All', NULL);
INSERT INTO CLIENTGROUP (ID, SNAME, OUTERID)
                 VALUES (3, 'Новые', NULL);
INSERT INTO CLIENTGROUP (ID, SNAME, OUTERID)
                 VALUES (0, 'Просто группа', NULL);

COMMIT WORK;

DELETE FROM ROUTES;
COMMIT WORK;

INSERT INTO ROUTES (ID, SNAME, OUTERID)
            VALUES (81, '1-понед', 1);
INSERT INTO ROUTES (ID, SNAME, OUTERID)
            VALUES (82, '2-вторн', 2);
INSERT INTO ROUTES (ID, SNAME, OUTERID)
            VALUES (-1, 'All', NULL);
INSERT INTO ROUTES (ID, SNAME, OUTERID)
            VALUES (0, 'Н/д', NULL);

COMMIT WORK;

DELETE FROM CLIENT;
COMMIT WORK;

INSERT INTO CLIENT (ID, AGENTID, PARENTID, NAME, DEBTSUMM1, DEBTDAYS1, DEBTSUMM2, DEBTDAYS2, STOPSHIPMENT, ROUTEID, DEFAULTDISCOUNT, NOACTIVE, ADDRESSLOCATION, PHONE, TAXCODE, TAXNUM, OKPO, MFO, BANKNAME, BANKACCOUNT, DOGNUM, FNAME, ADDRESSLAW, CLIENTTYPEID, LONGITUDE, LATITUDE, OUTERID)
            VALUES (2, 444, 0, 'Client2', 0, 0, 0, 0, 1, 0, 0, 1, 'ADDRESSLOCATION2', '050-381-25-17', '', '', '', '', '', '', '', '', '', 0, 123, 5666, 5465);
INSERT INTO CLIENT (ID, AGENTID, PARENTID, NAME, DEBTSUMM1, DEBTDAYS1, DEBTSUMM2, DEBTDAYS2, STOPSHIPMENT, ROUTEID, DEFAULTDISCOUNT, NOACTIVE, ADDRESSLOCATION, PHONE, TAXCODE, TAXNUM, OKPO, MFO, BANKNAME, BANKACCOUNT, DOGNUM, FNAME, ADDRESSLAW, CLIENTTYPEID, LONGITUDE, LATITUDE, OUTERID)
            VALUES (3, 444, 0, 'Клиент3', 0, 0, 0, 0, 0, 0, 0, 0, 'ADDRESSLOCATION3', '044-462-99-99', '', '', '', '', '', '', '', '', '', 0, 0, 0, 10865);
INSERT INTO CLIENT (ID, AGENTID, PARENTID, NAME, DEBTSUMM1, DEBTDAYS1, DEBTSUMM2, DEBTDAYS2, STOPSHIPMENT, ROUTEID, DEFAULTDISCOUNT, NOACTIVE, ADDRESSLOCATION, PHONE, TAXCODE, TAXNUM, OKPO, MFO, BANKNAME, BANKACCOUNT, DOGNUM, FNAME, ADDRESSLAW, CLIENTTYPEID, LONGITUDE, LATITUDE, OUTERID)
            VALUES (4, 444, 0, 'Клиент4', 0, 0, 0, 0, 0, 0, 0, 0, 'ADDRESSLOCATION4', '044-238-45-90', '', '', '', '', '', '', '', '', '', 0, 0, 0, 15198);
INSERT INTO CLIENT (ID, AGENTID, PARENTID, NAME, DEBTSUMM1, DEBTDAYS1, DEBTSUMM2, DEBTDAYS2, STOPSHIPMENT, ROUTEID, DEFAULTDISCOUNT, NOACTIVE, ADDRESSLOCATION, PHONE, TAXCODE, TAXNUM, OKPO, MFO, BANKNAME, BANKACCOUNT, DOGNUM, FNAME, ADDRESSLAW, CLIENTTYPEID, LONGITUDE, LATITUDE, OUTERID)
            VALUES (5, 444, 0, 'Клиент5', 0, 0, 0, 0, 0, 0, 0, 0, 'ADDRESSLOCATION5', '044-200-13-56', '', '', '', '', '', '', '', '', '', 0, 0, 0, 15221);
INSERT INTO CLIENT (ID, AGENTID, PARENTID, NAME, DEBTSUMM1, DEBTDAYS1, DEBTSUMM2, DEBTDAYS2, STOPSHIPMENT, ROUTEID, DEFAULTDISCOUNT, NOACTIVE, ADDRESSLOCATION, PHONE, TAXCODE, TAXNUM, OKPO, MFO, BANKNAME, BANKACCOUNT, DOGNUM, FNAME, ADDRESSLAW, CLIENTTYPEID, LONGITUDE, LATITUDE, OUTERID)
            VALUES (6, 444, 0, 'Клиент6', 0, 0, 0, 0, 0, 0, 0, 0, 'ADDRESSLOCATION6', '044-200-13-56', '', '', '', '', '', '', '', '', '', 0, 0, 0, 15222);
INSERT INTO CLIENT (ID, AGENTID, PARENTID, NAME, DEBTSUMM1, DEBTDAYS1, DEBTSUMM2, DEBTDAYS2, STOPSHIPMENT, ROUTEID, DEFAULTDISCOUNT, NOACTIVE, ADDRESSLOCATION, PHONE, TAXCODE, TAXNUM, OKPO, MFO, BANKNAME, BANKACCOUNT, DOGNUM, FNAME, ADDRESSLAW, CLIENTTYPEID, LONGITUDE, LATITUDE, OUTERID)
            VALUES (7, 444, 0, 'Клиент7', 0, 0, 0, 0, 0, 0, 0, 0, 'ADDRESSLOCATION7', '044-259-38-97', '', '', '', '', '', '', '', '', '', 0, 0, 0, 15230);
INSERT INTO CLIENT (ID, AGENTID, PARENTID, NAME, DEBTSUMM1, DEBTDAYS1, DEBTSUMM2, DEBTDAYS2, STOPSHIPMENT, ROUTEID, DEFAULTDISCOUNT, NOACTIVE, ADDRESSLOCATION, PHONE, TAXCODE, TAXNUM, OKPO, MFO, BANKNAME, BANKACCOUNT, DOGNUM, FNAME, ADDRESSLAW, CLIENTTYPEID, LONGITUDE, LATITUDE, OUTERID)
            VALUES (8, 444, 0, 'Клиент8', 0, 0, 0, 0, 0, 0, 0, 0, 'ADDRESSLOCATION8', '045-5-43-09,050', '', '', '', '', '', '', '', '', '', 0, 31.781601, 50.238049, 15250);
INSERT INTO CLIENT (ID, AGENTID, PARENTID, NAME, DEBTSUMM1, DEBTDAYS1, DEBTSUMM2, DEBTDAYS2, STOPSHIPMENT, ROUTEID, DEFAULTDISCOUNT, NOACTIVE, ADDRESSLOCATION, PHONE, TAXCODE, TAXNUM, OKPO, MFO, BANKNAME, BANKACCOUNT, DOGNUM, FNAME, ADDRESSLAW, CLIENTTYPEID, LONGITUDE, LATITUDE, OUTERID)
            VALUES (9, 444, 0, 'Клиент9', 0, 0, 0, 0, 0, 0, 0, 0, 'ADDRESSLOCATION9', '04594-3-44-38', '', '', '', '', '', '', '', '', '', 0, 0, 0, 15257);
INSERT INTO CLIENT (ID, AGENTID, PARENTID, NAME, DEBTSUMM1, DEBTDAYS1, DEBTSUMM2, DEBTDAYS2, STOPSHIPMENT, ROUTEID, DEFAULTDISCOUNT, NOACTIVE, ADDRESSLOCATION, PHONE, TAXCODE, TAXNUM, OKPO, MFO, BANKNAME, BANKACCOUNT, DOGNUM, FNAME, ADDRESSLAW, CLIENTTYPEID, LONGITUDE, LATITUDE, OUTERID)
            VALUES (10, 444, 0, 'Клиент10', 0, 0, 0, 0, 0, 0, 0, 0, 'ADDRESSLOCATION10', '067-231-22-65', '', '', '', '', '', '', '', '', '', 0, 0, 0, 15271);
INSERT INTO CLIENT (ID, AGENTID, PARENTID, NAME, DEBTSUMM1, DEBTDAYS1, DEBTSUMM2, DEBTDAYS2, STOPSHIPMENT, ROUTEID, DEFAULTDISCOUNT, NOACTIVE, ADDRESSLOCATION, PHONE, TAXCODE, TAXNUM, OKPO, MFO, BANKNAME, BANKACCOUNT, DOGNUM, FNAME, ADDRESSLAW, CLIENTTYPEID, LONGITUDE, LATITUDE, OUTERID)
            VALUES (11, 444, 0, 'Клиент11', 0, 0, 0, 0, 0, 0, 0, 0, 'ADDRESSLOCATION11', '050-443-53-22', '', '', '', '', '', '', '', '', '', 0, 0, 0, 15323);

            
COMMIT WORK;